services:
  postgresql:
    container_name: postgresql
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - incident_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  incident_api_service:
    container_name: incident_api_service
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - incident_network

volumes:
  postgres_data:
    driver: local

networks:
  incident_network:
    driver: bridge